In [41]:
# Importing packages
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import pyarrow

We are still working with the month of January 2021 for the power dataset

In [42]:
path_P = "../21-01/year_month=21-01/plugin=ipmi_pub/metric=total_power/a_0.parquet"
dataset_P = pd.read_parquet(path_P, engine='pyarrow')

# Casting of node values into integers
dataset_P['node'] = dataset_P['node'].astype(int)

dataset_P

                          timestamp  value  node
0         2021-01-21 06:42:40+00:00    700   128
1         2021-01-21 06:43:00+00:00    700   128
2         2021-01-21 06:43:20+00:00    580   128
3         2021-01-21 06:43:40+00:00    700   128
4         2021-01-21 06:44:00+00:00    680   128
...                             ...    ...   ...
112525874 2021-01-22 16:19:00+00:00    540   968
112525875 2021-01-22 16:19:20+00:00    540   968
112525876 2021-01-22 16:19:40+00:00    560   968
112525877 2021-01-22 16:20:00+00:00    540   968
112525878 2021-01-22 16:20:20+00:00    540   968

[112525879 rows x 3 columns]

In [43]:
# As usual I need to order by datetime the samples I have
dataset_P['timestamp'] = pd.to_datetime(dataset_P['timestamp'])

dataset_P = dataset_P.sort_values(by='timestamp')

dataset_P

                         timestamp  value  node
60022508 2021-01-01 00:00:00+00:00    440   421
52830690 2021-01-01 00:00:00+00:00    400   108
57252666 2021-01-01 00:00:00+00:00    560   130
56478061 2021-01-01 00:00:00+00:00    740   218
56287964 2021-01-01 00:00:00+00:00   1440   757
...                            ...    ...   ...
69552147 2021-01-31 23:43:40+00:00    540   882
69376636 2021-01-31 23:43:40+00:00    620    47
68539502 2021-01-31 23:43:40+00:00    600   304
68192463 2021-01-31 23:43:40+00:00    520    90
69552341 2021-01-31 23:43:40+00:00    480   891

[112525879 rows x 3 columns]

In [44]:
# Pivot the DataFrame
pivot_df = dataset_P.pivot(index='timestamp', columns='node')

# If you want to reset index (optional)
pivot_df.reset_index(inplace=True)

# Interpolate missing values using linear interpolation for each column
#for column in pivot_df.columns:
    #pivot_df[column].interpolate(method='linear', inplace=True)

# Display the resulting DataFrame with missing values filled using linear interpolation
pivot_df

                       timestamp  value                                     \
node                                  0      1      2      3      4      5
0      2021-01-01 00:00:00+00:00  380.0  420.0  420.0  360.0  440.0  400.0
1      2021-01-01 00:00:20+00:00  360.0  400.0  420.0  380.0  440.0  400.0
2      2021-01-01 00:00:40+00:00  360.0  400.0  420.0  360.0  440.0  400.0
3      2021-01-01 00:01:00+00:00  360.0  400.0  420.0  360.0  440.0  400.0
4      2021-01-01 00:01:20+00:00  360.0  400.0  420.0  380.0  440.0  400.0
...                          ...    ...    ...    ...    ...    ...    ...
115257 2021-01-31 23:30:40+00:00  440.0  400.0  400.0  360.0  420.0  400.0
115258 2021-01-31 23:31:00+00:00  420.0    NaN  400.0    NaN    NaN  380.0
115259 2021-01-31 23:43:00+00:00    NaN    NaN    NaN    NaN    NaN    NaN
115260 2021-01-31 23:43:20+00:00    NaN  400.0  420.0    NaN    NaN    NaN
115261 2021-01-31 23:43:40+00:00  440.0  400.0  420.0    NaN    NaN    NaN

                             ...                                            \
node        6      7      8  ...    970    971    972    973    974    975
0       440.0  420.0  420.0  ...  740.0  440.0  500.0  480.0  460.0  480.0
1       440.0  420.0  420.0  ...  580.0  440.0  500.0  480.0  480.0  460.0
2       440.0  420.0  420.0  ...  620.0  440.0  520.0  480.0  480.0  460.0
3       440.0  420.0  420.0  ...  620.0  440.0  520.0  480.0  460.0  480.0
4       440.0  420.0  420.0  ...  860.0  460.0  520.0  500.0  480.0  460.0
...       ...    ...    ...  ...    ...    ...    ...    ...    ...    ...
115257  440.0  420.0  420.0  ...  500.0  560.0  500.0  420.0  480.0  560.0
115258  440.0  420.0  420.0  ...    NaN    NaN    NaN    NaN    NaN    NaN
115259    NaN    NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN
115260    NaN    NaN  420.0  ...  500.0  560.0    NaN  420.0  460.0    NaN
115261    NaN  420.0  420.0  ...  480.0  560.0    NaN  440.0  600.0    NaN


node      976    977    978    979
0       400.0  760.0  760.0  480.0
1       400.0  700.0  600.0  480.0
2       400.0  700.0  540.0  480.0
3       400.0  680.0  640.0  480.0
4       400.0  840.0  580.0  480.0
...       ...    ...    ...    ...
115257  460.0  500.0  540.0  500.0
115258  560.0    NaN  480.0    NaN
115259    NaN    NaN    NaN    NaN
115260  480.0  500.0    NaN  500.0
115261  460.0  500.0    NaN  500.0

[115262 rows x 981 columns]

In [45]:
# Assuming 'datetime' column is already in datetime format
pivot_df['timestamp'] = pd.to_datetime(pivot_df['timestamp'])

# Set 'datetime' column as the index
pivot_df.set_index('timestamp', inplace=True)

# Resample the DataFrame on an hourly basis and calculate the sum
hourly_sum = pivot_df.resample('1H').sum()

# Display the resulting DataFrame
hourly_sum

                             value                                      \
node                           0        1        2        3        4
timestamp
2021-01-01 00:00:00+00:00  65920.0  72640.0  74980.0  65780.0  79100.0
2021-01-01 01:00:00+00:00  66480.0  73000.0  75060.0  65300.0  78780.0
2021-01-01 02:00:00+00:00  66300.0  72660.0  75100.0  65960.0  78840.0
2021-01-01 03:00:00+00:00  66220.0  72420.0  74980.0  65540.0  78800.0
2021-01-01 04:00:00+00:00  66560.0  72740.0  74840.0  65360.0  78840.0
...                            ...      ...      ...      ...      ...
2021-01-31 19:00:00+00:00  12160.0  11220.0  11580.0  10140.0  11880.0
2021-01-31 20:00:00+00:00   7820.0   8000.0   4540.0   7300.0   8800.0
2021-01-31 21:00:00+00:00  20500.0  18800.0  12420.0  17360.0  20700.0
2021-01-31 22:00:00+00:00   7420.0   6800.0   7060.0   6160.0   7480.0
2021-01-31 23:00:00+00:00   6020.0   8800.0   9340.0   7200.0   8740.0

                                                                        ...  \
node                           5        6        7        8        9    ...
timestamp                                                               ...
2021-01-01 00:00:00+00:00  71120.0  80220.0  75820.0  75620.0  75680.0  ...
2021-01-01 01:00:00+00:00  70660.0  79960.0  75940.0  75760.0  75640.0  ...
2021-01-01 02:00:00+00:00  71000.0  80040.0  76220.0  75880.0  75680.0  ...
2021-01-01 03:00:00+00:00  71220.0  79940.0  76100.0  75800.0  75760.0  ...
2021-01-01 04:00:00+00:00  71260.0  80040.0  76240.0  76000.0  75680.0  ...
...                            ...      ...      ...      ...      ...  ...
2021-01-31 19:00:00+00:00  11160.0  12480.0  11980.0  11420.0  11760.0  ...
2021-01-31 20:00:00+00:00   7540.0   8500.0   8880.0   8420.0   7980.0  ...
2021-01-31 21:00:00+00:00  18560.0  20240.0  20320.0  20260.0  19760.0  ...
2021-01-31 22:00:00+00:00   6740.0   7620.0   7240.0   7200.0   7180.0  ...
2021-01-31 23:00:00+00:00   8360.0   5760.0   5900.0   9680.0   9240.0  ...

                                                                         \
node                            970      971      972      973      974
timestamp
2021-01-01 00:00:00+00:00  117020.0  82480.0  92580.0  86380.0  82660.0
2021-01-01 01:00:00+00:00  114460.0  82560.0  92640.0  86760.0  82620.0
2021-01-01 02:00:00+00:00  113980.0  82860.0  92220.0  86220.0  83240.0
2021-01-01 03:00:00+00:00  115720.0  82580.0  92580.0  86180.0  82400.0
2021-01-01 04:00:00+00:00  139140.0  82920.0  91360.0  86640.0  83020.0
...                             ...      ...      ...      ...      ...
2021-01-31 19:00:00+00:00   15100.0  13900.0  15020.0  12400.0  14220.0
2021-01-31 20:00:00+00:00   10460.0   6020.0  10180.0   5600.0  10100.0
2021-01-31 21:00:00+00:00   16280.0  22300.0  25320.0  20740.0  24620.0
2021-01-31 22:00:00+00:00    8920.0   9080.0   9180.0   7860.0   8620.0
2021-01-31 23:00:00+00:00   11160.0  11500.0  10920.0   9840.0   7200.0


node                           975       976       977       978      979
timestamp
2021-01-01 00:00:00+00:00  82900.0  108260.0  135600.0  114960.0  86400.0
2021-01-01 01:00:00+00:00  83060.0  174660.0  135920.0  116440.0  86080.0
2021-01-01 02:00:00+00:00  83080.0  172000.0  136120.0  119380.0  86040.0
2021-01-01 03:00:00+00:00  82820.0  169940.0  136040.0  116700.0  85940.0
2021-01-01 04:00:00+00:00  82600.0  174400.0  135500.0   83520.0  85800.0
...                            ...       ...       ...       ...      ...
2021-01-31 19:00:00+00:00  14560.0   13720.0   15160.0   10900.0  14680.0
2021-01-31 20:00:00+00:00   5660.0    9800.0    6580.0    9780.0   9800.0
2021-01-31 21:00:00+00:00  24400.0   24460.0   24380.0   23740.0  20160.0
2021-01-31 22:00:00+00:00   8700.0    8680.0    8800.0    8480.0   8880.0
2021-01-31 23:00:00+00:00   7400.0   12020.0   11660.0   10560.0  11980.0

[744 rows x 980 columns]

In [46]:
# Iterate over each column (node) in the DataFrame
for node in hourly_sum.columns:
    # Replace the values in the original DataFrame with the hourly sum values
    pivot_df[node] = hourly_sum[node]

# Convert the index (assuming it's the timestamp) to datetime
pivot_df.index = pd.to_datetime(pivot_df.index)

# Drop rows where minutes and seconds are not zero
pivot_df = pivot_df.drop(pivot_df.index[(pivot_df.index.minute != 0) | (pivot_df.index.second != 0)])

# Display the resulting DataFrame with only rows corresponding to exact hours
pivot_df

                             value                                      \
node                           0        1        2        3        4
timestamp
2021-01-01 00:00:00+00:00  65920.0  72640.0  74980.0  65780.0  79100.0
2021-01-01 01:00:00+00:00  66480.0  73000.0  75060.0  65300.0  78780.0
2021-01-01 02:00:00+00:00  66300.0  72660.0  75100.0  65960.0  78840.0
2021-01-01 03:00:00+00:00  66220.0  72420.0  74980.0  65540.0  78800.0
2021-01-01 04:00:00+00:00  66560.0  72740.0  74840.0  65360.0  78840.0
...                            ...      ...      ...      ...      ...
2021-01-31 08:00:00+00:00  49520.0  45200.0  46880.0  38420.0  49740.0
2021-01-31 11:00:00+00:00  21880.0  20000.0  19940.0  17800.0  21540.0
2021-01-31 13:00:00+00:00  17480.0  16000.0  16580.0  14460.0  17560.0
2021-01-31 18:00:00+00:00  22180.0  20800.0  21400.0  18880.0  22880.0
2021-01-31 22:00:00+00:00   7420.0   6800.0   7060.0   6160.0   7480.0

                                                                        ...  \
node                           5        6        7        8        9    ...
timestamp                                                               ...
2021-01-01 00:00:00+00:00  71120.0  80220.0  75820.0  75620.0  75680.0  ...
2021-01-01 01:00:00+00:00  70660.0  79960.0  75940.0  75760.0  75640.0  ...
2021-01-01 02:00:00+00:00  71000.0  80040.0  76220.0  75880.0  75680.0  ...
2021-01-01 03:00:00+00:00  71220.0  79940.0  76100.0  75800.0  75760.0  ...
2021-01-01 04:00:00+00:00  71260.0  80040.0  76240.0  76000.0  75680.0  ...
...                            ...      ...      ...      ...      ...  ...
2021-01-31 08:00:00+00:00  44740.0  50460.0  47680.0  47680.0  48060.0  ...
2021-01-31 11:00:00+00:00  19380.0  22500.0  20280.0  20640.0  20680.0  ...
2021-01-31 13:00:00+00:00  15420.0  18220.0  13520.0  17280.0  16800.0  ...
2021-01-31 18:00:00+00:00  20600.0  22440.0  19440.0  19760.0  21420.0  ...
2021-01-31 22:00:00+00:00   6740.0   7620.0   7240.0   7200.0   7180.0  ...

                                                                         \
node                            970      971      972      973      974
timestamp
2021-01-01 00:00:00+00:00  117020.0  82480.0  92580.0  86380.0  82660.0
2021-01-01 01:00:00+00:00  114460.0  82560.0  92640.0  86760.0  82620.0
2021-01-01 02:00:00+00:00  113980.0  82860.0  92220.0  86220.0  83240.0
2021-01-01 03:00:00+00:00  115720.0  82580.0  92580.0  86180.0  82400.0
2021-01-01 04:00:00+00:00  139140.0  82920.0  91360.0  86640.0  83020.0
...                             ...      ...      ...      ...      ...
2021-01-31 08:00:00+00:00   61740.0  56420.0  60440.0  53860.0  58340.0
2021-01-31 11:00:00+00:00   25560.0  24680.0  26500.0  21940.0  24000.0
2021-01-31 13:00:00+00:00   13440.0  21240.0  21280.0  18360.0  20960.0
2021-01-31 18:00:00+00:00   25720.0  25920.0  27940.0  22840.0  24400.0
2021-01-31 22:00:00+00:00    8920.0   9080.0   9180.0   7860.0   8620.0


node                           975       976       977       978      979
timestamp
2021-01-01 00:00:00+00:00  82900.0  108260.0  135600.0  114960.0  86400.0
2021-01-01 01:00:00+00:00  83060.0  174660.0  135920.0  116440.0  86080.0
2021-01-01 02:00:00+00:00  83080.0  172000.0  136120.0  119380.0  86040.0
2021-01-01 03:00:00+00:00  82820.0  169940.0  136040.0  116700.0  85940.0
2021-01-01 04:00:00+00:00  82600.0  174400.0  135500.0   83520.0  85800.0
...                            ...       ...       ...       ...      ...
2021-01-31 08:00:00+00:00  58240.0   56180.0   62580.0   58260.0  65800.0
2021-01-31 11:00:00+00:00  24640.0   23940.0   27300.0   24640.0  28500.0
2021-01-31 13:00:00+00:00  20100.0   19540.0   21840.0   20700.0  23720.0
2021-01-31 18:00:00+00:00  27320.0   24360.0   25560.0   25800.0  26600.0
2021-01-31 22:00:00+00:00   8700.0    8680.0    8800.0    8480.0   8880.0

[643 rows x 980 columns]

In [47]:
# Interpolate NaN values in each column using linear interpolation
pivot_df.interpolate(method='linear', inplace=True)

# Display the resulting DataFrame with NaN values filled using linear interpolation
pivot_df

                             value                                      \
node                           0        1        2        3        4
timestamp
2021-01-01 00:00:00+00:00  65920.0  72640.0  74980.0  65780.0  79100.0
2021-01-01 01:00:00+00:00  66480.0  73000.0  75060.0  65300.0  78780.0
2021-01-01 02:00:00+00:00  66300.0  72660.0  75100.0  65960.0  78840.0
2021-01-01 03:00:00+00:00  66220.0  72420.0  74980.0  65540.0  78800.0
2021-01-01 04:00:00+00:00  66560.0  72740.0  74840.0  65360.0  78840.0
...                            ...      ...      ...      ...      ...
2021-01-31 08:00:00+00:00  49520.0  45200.0  46880.0  38420.0  49740.0
2021-01-31 11:00:00+00:00  21880.0  20000.0  19940.0  17800.0  21540.0
2021-01-31 13:00:00+00:00  17480.0  16000.0  16580.0  14460.0  17560.0
2021-01-31 18:00:00+00:00  22180.0  20800.0  21400.0  18880.0  22880.0
2021-01-31 22:00:00+00:00   7420.0   6800.0   7060.0   6160.0   7480.0

                                                                        ...  \
node                           5        6        7        8        9    ...
timestamp                                                               ...
2021-01-01 00:00:00+00:00  71120.0  80220.0  75820.0  75620.0  75680.0  ...
2021-01-01 01:00:00+00:00  70660.0  79960.0  75940.0  75760.0  75640.0  ...
2021-01-01 02:00:00+00:00  71000.0  80040.0  76220.0  75880.0  75680.0  ...
2021-01-01 03:00:00+00:00  71220.0  79940.0  76100.0  75800.0  75760.0  ...
2021-01-01 04:00:00+00:00  71260.0  80040.0  76240.0  76000.0  75680.0  ...
...                            ...      ...      ...      ...      ...  ...
2021-01-31 08:00:00+00:00  44740.0  50460.0  47680.0  47680.0  48060.0  ...
2021-01-31 11:00:00+00:00  19380.0  22500.0  20280.0  20640.0  20680.0  ...
2021-01-31 13:00:00+00:00  15420.0  18220.0  13520.0  17280.0  16800.0  ...
2021-01-31 18:00:00+00:00  20600.0  22440.0  19440.0  19760.0  21420.0  ...
2021-01-31 22:00:00+00:00   6740.0   7620.0   7240.0   7200.0   7180.0  ...

                                                                         \
node                            970      971      972      973      974
timestamp
2021-01-01 00:00:00+00:00  117020.0  82480.0  92580.0  86380.0  82660.0
2021-01-01 01:00:00+00:00  114460.0  82560.0  92640.0  86760.0  82620.0
2021-01-01 02:00:00+00:00  113980.0  82860.0  92220.0  86220.0  83240.0
2021-01-01 03:00:00+00:00  115720.0  82580.0  92580.0  86180.0  82400.0
2021-01-01 04:00:00+00:00  139140.0  82920.0  91360.0  86640.0  83020.0
...                             ...      ...      ...      ...      ...
2021-01-31 08:00:00+00:00   61740.0  56420.0  60440.0  53860.0  58340.0
2021-01-31 11:00:00+00:00   25560.0  24680.0  26500.0  21940.0  24000.0
2021-01-31 13:00:00+00:00   13440.0  21240.0  21280.0  18360.0  20960.0
2021-01-31 18:00:00+00:00   25720.0  25920.0  27940.0  22840.0  24400.0
2021-01-31 22:00:00+00:00    8920.0   9080.0   9180.0   7860.0   8620.0


node                           975       976       977       978      979
timestamp
2021-01-01 00:00:00+00:00  82900.0  108260.0  135600.0  114960.0  86400.0
2021-01-01 01:00:00+00:00  83060.0  174660.0  135920.0  116440.0  86080.0
2021-01-01 02:00:00+00:00  83080.0  172000.0  136120.0  119380.0  86040.0
2021-01-01 03:00:00+00:00  82820.0  169940.0  136040.0  116700.0  85940.0
2021-01-01 04:00:00+00:00  82600.0  174400.0  135500.0   83520.0  85800.0
...                            ...       ...       ...       ...      ...
2021-01-31 08:00:00+00:00  58240.0   56180.0   62580.0   58260.0  65800.0
2021-01-31 11:00:00+00:00  24640.0   23940.0   27300.0   24640.0  28500.0
2021-01-31 13:00:00+00:00  20100.0   19540.0   21840.0   20700.0  23720.0
2021-01-31 18:00:00+00:00  27320.0   24360.0   25560.0   25800.0  26600.0
2021-01-31 22:00:00+00:00   8700.0    8680.0    8800.0    8480.0   8880.0

[643 rows x 980 columns]